WEB_DRIVER_LOC:           remote
OS_PLATFORM:              windows10
BROWSER:                  chrome

# Remote Webdriver Port
#WINDOWS10:                10.234.178.115
WINDOWS10:                10.16.166.234
WEBDRIVER_PORT:           4444

# Remote Robot Server Port
REMOTE_SERVER_PORT:       8270

# Max Delay for which framework wait for an Element to respond
ELEMENT_DELAY:            10

