test_url:             "https://cp4.qa.xcloudiq.com"
capwap_url:           "cp4r1-cwpm-01.qa.xcloudiq.com"
sw_connection_host:   "cp4r1.qa.xcloudiq.com"
tenant_username:      "xiqproductionqa+auto1-blr-tb1-cp4r1@gmail.com"
tenant_password:      "Extreme@123"
base_url:             "https://cp4-api.qa.xcloudiq.com"
aio_xiq: 0
iapi_base_url:        "https://cp4.qa.xcloudiq.com"
sw_capwap_url:        "cp4r1.qa.xcloudiq.com"
wing_capwap_url:      "cp4r1-wing.qa.xcloudiq.com"
CLOUD_GDC_URL:        "https://cp4.qa.xcloudiq.com"
test_rdc_url:         "https://cp4r1.qa.xcloudiq.com"
