test_url:             "https://int2.qa.xcloudiq.com"
capwap_url:           "int2r1-cwpm-01.qa.xcloudiq.com"
sw_connection_host:   "int2r1.qa.xcloudiq.com"
tenant_username:      "xiqproductionqa+auto1-blr-tb1-int2r1@gmail.com"
tenant_password:      "Extreme@123"
base_url:             "https://int2-api.qa.xcloudiq.com"
aio_xiq: 0
iapi_base_url:        "https://int2.qa.xcloudiq.com"
sw_capwap_url:        "int2r1.qa.xcloudiq.com"
wing_capwap_url:      "int2r1-wing.qa.xcloudiq.com"
CLOUD_GDC_URL:        "https://int2.qa.xcloudiq.com"
test_rdc_url:         "https://int2r1.qa.xcloudiq.com"
