cmd_capwap_client_state:          show capwap client | include state
cmd_capwap_hm_primary_name:       show capwap client | include "HiveManager Primary Name"
cmd_capwap_server_ip:             show capwap client | include "CAPWAP server IP"
cmd_capwap_primary_name:          show capwap client | include "HiveManager Primary Name"
cmd_show_process_eciq:            show process | include eciq
#output_capwap_status:             Connected securely to the CAPWAP server
output_capwap_status:             Enabled
output_process_eciq:              Ready
cmd_clear_client_mac:             clear auth station mac  MU1_WIFI_MAC
cmd_show_station:                 show station
cmd_console_page_0:               console page 0
cmd_show_version_detail:          show version detail
cmd_show_capwap_client:           show capwap client
cmd_boot_param:                   show boot-param | include "Country Code"