import random

RANDOM_INT = random.randint(0, 999)

VOSS_POLICY_NAME   =       f"VOSS_POLICY_{RANDOM_INT}"
VOSS_SSID_NAME     =       f"VOSS_SSID_{RANDOM_INT}"
VOSS_TEMPLATE_NAME =       f"VOSS_TEMPLATE_{RANDOM_INT}"

