#!/usr/bin/env python
# -*- coding: UTF-8 -*-
import os
import sys
import cgi
import cgitb


UPLOAD_DIR = "upload_files"
MY_FILE = "upload_bundle.tgz"

# Uncomment to show nice errors to the browser
#cgitb.enable()

## Note that the basic http.server being used for this always sends status 200

form = cgi.FieldStorage()

if "file" not in form:
    print('Content-Type: text/html; charset=utf-8\n')
    print("<h2>File element missing</h2>")
    sys.exit()

fileitem = form["file"]

if fileitem.filename:
    # strip the leading path from the file name
    fn = os.path.join(UPLOAD_DIR, os.path.basename(fileitem.filename))
else:
    fn = os.path.join(UPLOAD_DIR, MY_FILE)

# open read and write the file into the server
open(fn, 'wb').write(fileitem.file.read())
print('Content-Type: text/html; charset=utf-8\n')
print("<h2>File Uploaded: {}</h2>".format(fn))
