test_url:             "https://extremecloudiq.com"
capwap_url:           "redirector.aerohive.com"
sw_capwap_url:        "aca.extremecloudiq.com"
wing_capwap_url:      "aca-wing.extremecloudiq.com"
tenant_username:      "qepostlivetest@extremenetworks.com"
tenant_password:      "agxRgMvNVaT87Q2#"
tenant_ext_name:      "C ACA Calgary Board of Education"
base_url:             "https://api.extremecloudiq.com"
test_rdc_url:         "https://aca.extremecloudiq.com"
network_policy:       "CBE-LIVE"
ssid:                 "LIVE-CBE-Open"