test_url:             "https://extremecloudiq.com"
capwap_url:           "redirector.aerohive.com"
sw_capwap_url:        "va2.extremecloudiq.com"
wing_capwap_url:      "va2-wing.extremecloudiq.com"
tenant_username:      "qepostlivetest@extremenetworks.com"
tenant_password:      "agxRgMvNVaT87Q2#"
tenant_ext_name:      "C VA2 THE SCHOOL DISTRICT OF PALM BEACH"
base_url:             "https://api.extremecloudiq.com"
test_rdc_url:         "https://va2.extremecloudiq.com"
network_policy:       "All-Sites"
ssid:                 "Districtwifi"
