WEB_DRIVER_LOC:           remote
OS_PLATFORM:              windows10
BROWSER:                  chrome

# Configure this to True to print the WebElement descriptions in definitions
ELEMENT_INFO:             None

# Remote Webdriver Port
WINDOWS10:                10.234.188.125
WEBDRIVER_PORT:           4444

# Max Delay for which framework wait for an Element to respond
ELEMENT_DELAY:            10