test_url:             "https://cp7.qa.xcloudiq.com"
capwap_url:           "cp7r1-cwpm-01.qa.xcloudiq.com"
sw_connection_host:   "cp7r1.qa.xcloudiq.com"
tenant_username:      "xiqproductionqa+auto1-blr-tb1-cp7r1@gmail.com"
tenant_password:      "Extreme@123"
xapi_url:             "https://cp7-api.qa.xcloudiq.com"
base_url:             "https://cp7-api.qa.xcloudiq.com"
aio_xiq: 0
iapi_base_url:        "https://cp7.qa.xcloudiq.com"
sw_capwap_url:        "cp7r1.qa.xcloudiq.com"
wing_capwap_url:      "cp7r1-wing.qa.xcloudiq.com"
CLOUD_GDC_URL:        "https://cp7.qa.xcloudiq.com"
test_rdc_url:         "https://cp7r1.qa.xcloudiq.com"
server_name:          "qa-redirector.extremecloudiq.com"
