test_url:                 "https://tme1.qa.xcloudiq.com"
capwap_url:               "tme1r1-cwm.qa.xcloudiq.com"
sw_capwap_url:            "tme1r1.qa.xcloudiq.com"
tenant_username:          "xiqproductionqa+auto1-blr-tb1-tme1r1@gmail.com"
tenant_password:          "Extreme@123"
sw_connection_host:        "tme1r1.qa.xcloudiq.com"
wing_capwap_url:          "tme1r1-wing.qa.xcloudiq.com"
base_url:                 "https://tme1-api.qa.xcloudiq.com"
test_rdc_url:             "https://tme1r1.qa.xcloudiq.com"
CLOUD_GDC_URL:            "https://tme1.qa.xcloudiq.com"
server_name:              "qa-redirector.extremecloudiq.com"
