#Please find Steps to create unique Mail for private pre shared key test suite in Production Sanity in
#https://wiki.iq.extremenetworks.com/wiki/display/XBQ/Steps+to+create+unique+Mail+for+private+pre+shared+key+test+suite+in+Production+Sanity
test_url:                 "https://qa-e1.qa.xcloudiq.com"
capwap_url:               "qa-redirector.extremecloudiq.com"
sw_capwap_url:            "qa-e1r1.qa.xcloudiq.com"
tenant_username:          "xiqproductionqa+auto1-blr-tb1-e1r1@gmail.com"
tenant_password:          "Extreme@123"
sw_connection_host:       "qa-e1r1.qa.xcloudiq.com"
wing_capwap_url:          "qa-e1r1-wing.qa.xcloudiq.com"
base_url:                 "https://qa-e1-api.qa.xcloudiq.com"
test_rdc_url:             "https://qa-e1r1.qa.xcloudiq.com"
CLOUD_GDC_URL:            "https://qa-e1.qa.xcloudiq.com"
server_name:              "qa-redirector.extremecloudiq.com"
PPSK_MAIL_ID:             "mail.ppsk.e1r1@gmail.com"
PPSK_MAIL_PASSWORD:       "idhwlbiczmslbsnj"