#Please find Steps to create unique Mail for private pre shared key test suite in Production Sanity in
#https://wiki.iq.extremenetworks.com/wiki/display/XBQ/Steps+to+create+unique+Mail+for+private+pre+shared+key+test+suite+in+Production+Sanity
test_url:                 "https://cp9.qa.xcloudiq.com"
capwap_url:               "cp9r1-cwpm-01.qa.xcloudiq.com"
sw_capwap_url:            "cp9r1.qa.xcloudiq.com"
tenant_username:          "xiqextremeqa+auto1-cp9r1@gmail.com"
tenant_password:          "Extreme@123"
sw_connection_host:       "cp9r1.qa.xcloudiq.com"
wing_capwap_url:          "cp9r1-wing.qa.xcloudiq.com"
xapi_url:                 "https://cp9-api.qa.xcloudiq.com"
base_url:                 "https://cp9-api.qa.xcloudiq.com"
test_rdc_url:             "https://cp9r1.qa.xcloudiq.com"
CLOUD_GDC_URL:            "https://cp9.qa.xcloudiq.com"
server_name:              "qa-redirector.extremecloudiq.com"
PPSK_MAIL_ID:             "mail.ppsk.cp9@gmail.com"
PPSK_MAIL_PASSWORD:       "qmkmnbdyijkdounc"