test_url:                 "https://g2.qa.xcloudiq.com"
capwap_url:               "g2r1-cwpm-01.qa.xcloudiq.com"
sw_capwap_url:            "g2r1.qa.xcloudiq.com"
xapi_url:                 "https://g2-api.qa.xcloudiq.com"
tenant_username:          "xiqextremeqa+msp-g2r1@gmail.com"
tenant_password:          "Extreme@123"
organization_name:        "TEST_ORG"
sw_connection_host:       "g2r1.qa.xcloudiq.com"
wing_capwap_url:          "g2r1-wing.qa.xcloudiq.com"
base_url:                 "https://g2-api.qa.xcloudiq.com"
test_rdc_url:             "https://g2r1.qa.xcloudiq.com"
CLOUD_GDC_URL:            "https://g2.qa.xcloudiq.com"
server_name:              "qa-redirector.extremecloudiq.com"