#Please find Steps to create unique Mail for private pre shared key test suite in Production Sanity in
#https://wiki.iq.extremenetworks.com/wiki/display/XBQ/Steps+to+create+unique+Mail+for+private+pre+shared+key+test+suite+in+Production+Sanity
test_url:                 "https://g2.qa.xcloudiq.com"
capwap_url:               "qa-redirector.extremecloudiq.com"
sw_capwap_url:            "g2r1.qa.xcloudiq.com"
xapi_url:                 "https://g2-api.qa.xcloudiq.com"
tenant_username:          "xiqextremeqa+auto1-blr_tb1-g2r1@gmail.com"
tenant_password:          "Extreme@123"
sw_connection_host:       "g2r1.qa.xcloudiq.com"
wing_capwap_url:          "g2r1-wing.qa.xcloudiq.com"
base_url:                 "https://g2-api.qa.xcloudiq.com"
test_rdc_url:             "https://g2r1.qa.xcloudiq.com"
CLOUD_GDC_URL:            "https://g2.qa.xcloudiq.com"
server_name:              "qa-redirector.extremecloudiq.com"
PPSK_MAIL_ID:             "mail.ppsk.g2r1@gmail.com"
PPSK_MAIL_PASSWORD:       "bibkrtfaweelcctr"